export const assetNotice = 'All companion and sports assets are preview-only. Sales are disabled.';
export const integrationNotice = 'External companions require an explicit structured integration and a separately launched companion pane, not universal automatic native hooks. Gemini hooks are observation-only: no live waiting or completion animation. Claude hooks are activity-only and never trigger completion celebrations. The explicit process wrapper observes whole-process exit, not individual answers.';
export const modelBoundary = 'Backend model routing is separate from external CLI emote compatibility.';
export const campaigns = [
  {id:'companions', name:'Pixel People', kicker:'A little company for the work ahead.', description:'Meet the cast, find a rhythm, explore a new horizon.', status:'Concept-approved character art. Separate companion pane conditionally approved as the currently safe first-release UX. Final terminal animation review remains; same-window UX is a later requirement.'},
  {id:'sports', name:'The Finish Feels Different', kicker:'A three-act completion celebration.', description:'Warm up, hit the finish, settle back into focus.', status:'Unreleased sports completion-emote preview. Stable humans-only authored packs are integrated with original provenance. Final art approval and native-terminal animation review remain pending.'},
  {id:'models', name:'Choose Your Route', kicker:'Backend-funded compute, drawn as a transit atlas.', description:'Fund the route, choose a model, change direction.', status:'Backend-funded multi-model switching campaign preview. Selection depends on account, backend funding, catalog, and provider availability. No shared-context or provider-subscription claim.'},
  {id:'arcade', name:'Work Has A Side Quest', kicker:'One direct path. An optional detour.', description:'Use credits directly, explore the arcade, keep the choice yours.', status:'Product-flow illustration, not a balance, payout, or live game recording. Games can win or lose credits. No return or runtime guarantee.'},
];
for (const campaign of campaigns) {
  campaign.status += ' ' + assetNotice;
  if (['companions','sports'].includes(campaign.id)) campaign.status += ' ' + integrationNotice;
  if (campaign.id === 'models') campaign.status += ' ' + modelBoundary;
}
export const slides = [
  {id:'companions-01',campaign:'companions',theme:'light',layout:'cast',eyebrow:'01 / MEET THE CAST',title:'Meet your<br><em>pixel people.</em>',lede:'A courier. A beat maker. An explorer.<br>Small pixels. Very different energies.',footer:'[ A LITTLE COMPANY ]',alt:'Three original pixel companions stand across an aqua editorial stage: Pixel Courier, Beat Maker and Visor Explorer.',caption:'Meet the OpenVegas pixel companions: a courier, a beat maker, and an explorer. Original concept-approved art in a campaign preview; terminal animation and release review are pending.'},
  {id:'companions-02',campaign:'companions',theme:'dark',layout:'rhythm',eyebrow:'02 / FIND YOUR RHYTHM',title:'You compute.<br><em>They keep time.</em>',lede:'Let the work take focus.<br>Let a little personality keep you company.',footer:'[ IN YOUR OWN RHYTHM ]',alt:'Beat Maker dances in front of concentric record grooves, with two smaller authored poses framing the rhythm.',caption:'You compute. They keep time. Beat Maker brings personality to this companion-pane concept. Authored animation, not live terminal footage or a promise of universal overlay support. Separate companion pane conditionally approved for first release; final animation review and later same-window UX remain outstanding.'},
  {id:'companions-03',campaign:'companions',theme:'light',layout:'horizon',eyebrow:'03 / NEXT HORIZON',title:'Make room<br>for <em>wonder.</em>',lede:'Same workspace.<br>A whole new cast of characters.',footer:'[ FIND YOUR PEOPLE ]',alt:'Visor Explorer stands in a large orbital portal. Pixel Courier and Beat Maker appear as small constellation companions.',caption:'Make room for wonder. Visor Explorer, Pixel Courier and Beat Maker are original character previews, not purchasable premium packs. Final terminal-art and animation approval remains pending.'},
  {id:'sports-01',coverTime:6250,campaign:'sports',theme:'dark',layout:'warmup',eyebrow:'01 / THE WARM-UP',title:'Big focus.<br><em>Game energy.</em>',lede:'Before the finish,<br>find your rhythm.',footer:'[ LOCK IN ]',sportsSlot:'skyline-dunk',alt:'Skyline Dunk: an original blue-and-amber human basketball player dunks past a generic human defender. Four genuine authored poses form a dribble, leap, dunk and celebration filmstrip.',caption:'Skyline Dunk. An original human player dribbles, leaps, dunks and celebrates past a generic human defender. The emote uses twelve authored poses over a 5.4-second completion clip. Unreleased preview, not live CLI footage; final art approval and terminal animation review pending. No real athlete or team endorsement.'},
  {id:'sports-02',coverTime:5700,campaign:'sports',theme:'light',layout:'finish',eyebrow:'02 / THE FINISH',title:'Task done.<br><em>What a finish.</em>',lede:'A completion-emote<br>concept, in motion.',footer:'[ THAT FINISH-LINE FEELING ]',sportsSlot:'bicycle-finish',alt:'Bicycle Finish: an original human footballer performs an overhead kick toward a generic human goalkeeper. A four-pose filmstrip shows setup, flight, strike and celebration.',caption:'Task done. What a finish. Bicycle Finish shows an original human footballer and a generic human goalkeeper in a 5.4-second authored action. Process completion does not certify task correctness. Unreleased emote preview, not live product footage; final art approval and terminal animation review remain pending.'},
  {id:'sports-03',coverTime:8200,campaign:'sports',theme:'dark',layout:'cooldown',eyebrow:'03 / BACK TO FOCUS',title:'One celebration.<br><em>Then, ready.</em>',lede:'The moment lands.<br>The work gets the stage again.',footer:'[ READY FOR WHAT IS NEXT ]',sportsSlot:'three-point-glow',alt:'Three Point Glow: an original human basketball player takes a shot against a generic human defender, then celebrates. Four authored poses show setup, release, basket and celebration beneath the large action frame.',caption:'One celebration. Then, ready. Three Point Glow shows an original human basketball player and human defender. In this authored preview, the 5.4-second completion clip plays once, then returns to idle. Unreleased preview: final art approval, trigger integration and native-terminal review remain release dependencies. No real team or athlete endorsement.'},
  {id:'models-01',campaign:'models',theme:'light',layout:'fund',eyebrow:'01 / FUND THE ROUTE',title:'One balance.<br><em>More directions.</em>',lede:'Fund compute through OpenVegas.<br>Choose from the available models.',footer:'[ TOP UP / REDEEM / RUN ]',alt:'Pixel Courier stands at the origin of an illustrated transit map: OpenVegas balance routes through the backend to available models.',caption:'Choose your route. Campaign preview of backend-funded compute through OpenVegas: balance, backend, available model. Availability depends on account, funding, catalog, and provider configuration. Not a provider subscription, quota reset, or promise of unlimited use.'},
  {id:'models-02',campaign:'models',theme:'dark',layout:'switch',eyebrow:'02 / CHOOSE YOUR MODEL',title:'Different models.<br><em>Your call.</em>',lede:'A new task can call for<br>a different route.',footer:'[ CHOOSE WHAT FITS ]',alt:'Visor Explorer stands at an aqua transit junction with branches marked OpenAI, Anthropic and available catalog. Routes are illustrative, not a product screenshot.',caption:'Different models. Your call. Backend-funded multi-model switching campaign preview, subject to the enabled catalog, account and provider availability. The route map is illustrative. No automatic routing, universal model access, or shared cross-provider context is implied.'},
  {id:'models-03',campaign:'models',theme:'light',layout:'perspective',eyebrow:'03 / CHANGE DIRECTION',title:'Same desk.<br><em>Another lens.</em>',lede:'Select a model for the next request.<br>Keep the choice in your hands.',footer:'[ YOUR NEXT DIRECTION ]',alt:'Three tall perspective windows surround the companion cast, suggesting three different model viewpoints without depicting a real application.',caption:'Same desk. Another lens. A campaign concept for choosing an available model for a request with OpenVegas-funded compute. Cross-model context continuity and automatic switching are not claimed. Review backend funding and account availability before publication.'},
  {id:'arcade-01',campaign:'arcade',theme:'dark',layout:'direct',eyebrow:'01 / THE DIRECT PATH',title:'Credits in.<br><em>Ideas out.</em>',lede:'Top up. Redeem for compute.<br>Games are never the required step.',footer:'[ KEEP WORKING ]',alt:'Pixel Courier follows a bright direct path from credits to compute, with a small side branch marked optional arcade.',caption:'Credits in. Ideas out. OpenVegas credits can be used directly for AI compute. Games are optional, not a prerequisite. Illustration only; account and provider availability apply. No guarantee of output quality, runtime extension, or financial return.'},
  {id:'arcade-02',campaign:'arcade',theme:'light',layout:'play',eyebrow:'02 / THE OPTIONAL DETOUR',title:'Work has<br>a <em>side quest.</em>',lede:'Horse. Blackjack. Roulette.<br>An arcade beside the compute path.',footer:'[ PLAY IS OPTIONAL ]',risk:'Games can win or lose credits.',alt:'Beat Maker and Pixel Courier frame a large abstract roulette-inspired disc and editorial labels for horse, blackjack and roulette. No game outcome is shown.',caption:'Work has a side quest. OpenVegas offers horse, blackjack, roulette and other games as an optional credit path. Games can win or lose credits. This is original campaign artwork, not a live game, offer, payout claim, or promise of profit.'},
  {id:'arcade-03',campaign:'arcade',theme:'dark',layout:'choice',eyebrow:'03 / YOUR CALL',title:'Make room<br>for <em>more.</em>',lede:'Compute first. Arcade if you want.<br>Know your balance. Choose your next step.',footer:'[ THE CHOICE STAYS YOURS ]',risk:'Optional games. Credits can be lost.',alt:'The three pixel companions meet at a fork in the road, with a solid compute route and a separate optional play route. The composition emphasizes user choice, not winnings.',caption:'Make room for more. Fund AI usage directly, track balance and activity, or choose optional games. Games can win or lose credits; no guaranteed profit, runtime multiplier, or provider usage-limit reset. Product-flow illustration; current account and provider availability apply.'},
];
// Keep export captions inseparable from the current compatibility boundaries.
for (const slide of slides) {
  slide.caption += ' ' + assetNotice;
  if (['companions','sports'].includes(slide.campaign)) slide.caption += ' ' + integrationNotice;
  if (slide.campaign === 'models') slide.caption += ' ' + modelBoundary;
}
